// URLs without leading slashes
export const URLS_SHORT = {
  AUTH: {
    TITLE: 'auth',
    LOGIN: 'auth/login',
    REGISTER: 'auth/registration',
    FORGOT_PASSWORD: 'auth/forgot-password',
    INIT_PASSWORD: 'auth/init',
    LOGOUT: 'auth/logout',
  },
  ABOUT: {
    TITLE: 'about',
    TERMS: 'about/terms',
    IMPRINT: 'about/imprint',
    PRIVACY: 'about/privacy',
    SUSTAINABILITY: 'about/sustainability',
    RECIPES: 'about/recipes',
  },
  SCREENS: {
    TITLE: 'scenarios',
    BUBBLE: 'scenarios/bubble',
    PUZZLE: 'scenarios/puzzle',
  },
  DEVICE: {
    TITLE: 'device',
    CONNECT: 'device/connect',
  },
  ADMINISTRATION: {
    TITLE: 'administration',
    USERS: 'administration/users',
    ORDER: 'administration/order',
    ORDER_DETAIL: 'administration/order/detail',
    SETTINGS: 'administration/settings',
    PRODUCT: 'administration/product',
    PRODUCT_DETAIL: 'administration/product/detail',
    DISCOUNT: 'administration/discount',
    DISCOUNT_DETAIL: 'administration/discount/detail',

    SCREEN: 'administration/screen',
    SCREEN_DETAIL: 'administration/screens/detail',
    MASK: 'administration/mask',
    MASK_DETAIL: 'administration/masks/detail',
  }
}

// URLs with leading slashes but without trailing slashes
export const URLS = {
  HOME: '/',
  AUTH: {
    LOGIN: `/${URLS_SHORT.AUTH.LOGIN}`,
    REGISTER: `/${URLS_SHORT.AUTH.REGISTER}`,
    FORGOT_PASSWORD: `/${URLS_SHORT.AUTH.FORGOT_PASSWORD}`,
    INIT_PASSWORD: `/${URLS_SHORT.AUTH.INIT_PASSWORD}`,
    LOGOUT: `/${URLS_SHORT.AUTH.LOGOUT}`,
  },
  ABOUT: {
    TERMS: `/${URLS_SHORT.ABOUT.TERMS}`,
    IMPRINT: `/${URLS_SHORT.ABOUT.IMPRINT}`,
    PRIVACY: `/${URLS_SHORT.ABOUT.PRIVACY}`,
    SUSTAINABILITY: `/${URLS_SHORT.ABOUT.SUSTAINABILITY}`,
    RECIPES: `/${URLS_SHORT.ABOUT.RECIPES}`,
  },
  SCREENS: {
    TITLE: `/${URLS_SHORT.SCREENS.TITLE}`,
    BUBBLE: `/${URLS_SHORT.SCREENS.BUBBLE}`,
    PUZZLE: `/${URLS_SHORT.SCREENS.PUZZLE}`,
  },
  DEVICE: {
    TITLE: `/${URLS_SHORT.DEVICE.TITLE}`,
    CONNECT: `/${URLS_SHORT.DEVICE.CONNECT}`,
  },
  ADMINISTRATION: {
    USERS: `/${URLS_SHORT.ADMINISTRATION.USERS}`,
    ORDER: `/${URLS_SHORT.ADMINISTRATION.ORDER}`,
    ORDER_DETAIL: `/${URLS_SHORT.ADMINISTRATION.ORDER_DETAIL}`,
    SETTINGS: `/${URLS_SHORT.ADMINISTRATION.SETTINGS}`,
    PRODUCT: `/${URLS_SHORT.ADMINISTRATION.PRODUCT}`,
    PRODUCT_DETAIL: `/${URLS_SHORT.ADMINISTRATION.PRODUCT_DETAIL}`,
    DISCOUNT: `/${URLS_SHORT.ADMINISTRATION.DISCOUNT}`,
    DISCOUNT_DETAIL: `/${URLS_SHORT.ADMINISTRATION.DISCOUNT_DETAIL}`,

    SCREENS: `/${URLS_SHORT.ADMINISTRATION.SCREEN}`,
    SCREENS_DETAIL: `/${URLS_SHORT.ADMINISTRATION.SCREEN_DETAIL}`,
    MASKS: `/${URLS_SHORT.ADMINISTRATION.MASK}`,
    MASKS_DETAIL: `/${URLS_SHORT.ADMINISTRATION.MASK_DETAIL}`,
  }
}

// URLs with leading and trailing slashes
export const URLS_FULL = {
  HOME: '/',
  AUTH: {
    LOGIN: `/${URLS_SHORT.AUTH.LOGIN}/`,
    REGISTER: `/${URLS_SHORT.AUTH.REGISTER}/`,
    FORGOT_PASSWORD: `/${URLS_SHORT.AUTH.FORGOT_PASSWORD}/`,
    INIT_PASSWORD: `/${URLS_SHORT.AUTH.INIT_PASSWORD}/`,
    LOGOUT: `/${URLS_SHORT.AUTH.LOGOUT}/`,
  },
  ABOUT: {
    TERMS: `/${URLS_SHORT.ABOUT.TERMS}/`,
    IMPRINT: `/${URLS_SHORT.ABOUT.IMPRINT}/`,
    PRIVACY: `/${URLS_SHORT.ABOUT.PRIVACY}/`,
    SUSTAINABILITY: `/${URLS_SHORT.ABOUT.SUSTAINABILITY}/`,
    RECIPES: `/${URLS_SHORT.ABOUT.RECIPES}/`,
  },
  SCREENS: {
    TITLE: `/${URLS_SHORT.SCREENS.TITLE}/`,
    BUBBLE: `/${URLS_SHORT.SCREENS.BUBBLE}/`,
    PUZZLE: `/${URLS_SHORT.SCREENS.PUZZLE}/`,
  },
  DEVICE: {
    TITLE: `/${URLS_SHORT.DEVICE.TITLE}/`,
    CONNECT: `/${URLS_SHORT.DEVICE.CONNECT}/`,
  },
  ADMINISTRATION: {
    USERS: `/${URLS_SHORT.ADMINISTRATION.USERS}/`,
    ORDER: `/${URLS_SHORT.ADMINISTRATION.ORDER}/`,
    ORDER_DETAIL: `/${URLS_SHORT.ADMINISTRATION.ORDER_DETAIL}/`,
    SETTINGS: `/${URLS_SHORT.ADMINISTRATION.SETTINGS}/`,
    PRODUCT: `/${URLS_SHORT.ADMINISTRATION.PRODUCT}/`,
    PRODUCT_DETAIL: `/${URLS_SHORT.ADMINISTRATION.PRODUCT_DETAIL}/`,
    DISCOUNT: `/${URLS_SHORT.ADMINISTRATION.DISCOUNT}/`,
    DISCOUNT_DETAIL: `/${URLS_SHORT.ADMINISTRATION.DISCOUNT_DETAIL}/`,

    SCREENS: `/${URLS_SHORT.ADMINISTRATION.SCREEN}/`,
    SCREENS_DETAIL: `/${URLS_SHORT.ADMINISTRATION.SCREEN_DETAIL}/`,
    MASKS: `/${URLS_SHORT.ADMINISTRATION.MASK}/`,
    MASKS_DETAIL: `/${URLS_SHORT.ADMINISTRATION.MASK_DETAIL}/`,
  }
}